---
kind: pipeline
name: default

platform: 
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings: 
    registry: quay.io
    username:
      from_secret: QUAY_UNAME
    password:
      from_secret: QUAY_PWORD
    repo: calvinrodo/golangbuilder
    tags:
      - latest
      - 0.0.1